config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from django.contrib.auth.decorators import login_required
from django.conf.urls import include, url
from qr_code import urls as qr_code_urls

urlpatterns = [
    url(r"^$",
        TemplateView.as_view(template_name="pages/home.html"),
        name="home"),
    url(r'^contact/$',
        TemplateView.as_view(template_name='pages/contact.html'),
        name='contact'),
    url(r'^terms/$',
        TemplateView.as_view(template_name='pages/terms.html'),
        name='terms'),
    url(r'^privacy/$',
        TemplateView.as_view(template_name='pages/privacy.html'),
        name='privacy'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),
    # User management
    url(r"^users/", include("krvjezivot.users.urls", namespace="users")),
    url(r"^administration/", include("krvjezivot.administration.urls", namespace="administration")),
    url(r"^donations/", include("krvjezivot.donations.urls", namespace="donations")),
    url(r'^qr_code/', include(qr_code_urls, namespace="qr_code")),
    url(r"^accounts/", include("allauth.urls")),

    # Your stuff: custom urls includes go here
    url(r'^dashboard/',
        login_required(
            TemplateView.as_view(template_name='pages/dashboard.html')),
        name='dashboard')
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(
            r"^400/$",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        url(
            r"^403/$",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        url(
            r"^404/$",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        url(r"^500/$", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [url(r"^__debug__/", include(debug_toolbar.urls))
                       ] + urlpatterns

krvjezivot/administration/urls.py
from django.urls import path

from . import views

app_name = 'administration'

urlpatterns = [
    path(
        'venue/list',
        views.get_donation_venues_list,
        name='donation_venues_list'),
    path(
        'venue/add',
        views.DonationVenueFormView.as_view(),
        name='donation_venue_add'),
    path(
        'venue/<int:venue_id>',
        views.DonationVenueFormView.as_view(),
        name='donation_venue_details'),
    path(
        'venue/<int:venue_id>/update',
        views.DonationVenueFormView.as_view(),
        name='donation_venue_update'),
    path(
        'venue/<int:venue_id>/delete',
        views.donation_venue_delete,
        name='donation_venue_delete'),
    path(
        'event/list',
        views.get_donation_events_list,
        name='donation_events_list'),
    path(
        'event/add',
        views.DonationEventFormView.as_view(),
        name='donation_event_add'),
    path(
        'event/<int:event_id>',
        views.DonationEventFormView.as_view(),
        name='donation_event_details'),
    path(
        'event/<int:event_id>/update',
        views.DonationEventFormView.as_view(),
        name='donation_event_update'),
    path(
        'event/<int:event_id>/delete',
        views.donation_event_delete,
        name='donation_event_delete'),
    path(
        'qr_donation_confirm/<int:event_id>',
        views.get_donation_qr_confirm,
        name='get_donation_qr_confirm'),
    path(
        'qr_donation_confirm/<int:event_id>',
        views.user_donation_qr_confirm,
        name='user_donation_qr_confirm'),
]

krvjezivot/donations/urls.py
from django.urls import path

from . import views

app_name = 'donations'

urlpatterns = [
    path(
        'invite/list',
        views.get_donation_invites_list,
        name='donation_invites_list'),
    path(
        'invite/<int:invite_id>/confirm',
        views.donation_invite_confirm,
        name='donation_invite_confirm'),
    path(
        'invite/<int:invite_id>/deny',
        views.donation_invite_delete,
        name='donation_invite_deny'),
    path('qrcode', views.get_qrcode, name='user_qrcode'),
    path('history', views.get_donation_history, name='donation_history'),
]

krvjezivot/users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'
urlpatterns = [
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
]

krvjezivot/administration/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from krvjezivot.users.models import User

# Create your models here.


class DonationVenue(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(_("donation venue name"), max_length=255)
    address = models.CharField(_("donation venue address"), max_length=255)
    average_recall = models.FloatField(
        _('average recall percentage'), default=1.0)


class DonationEvent(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(_("event name"), max_length=255)
    event_start = models.CharField(
        _("event start date and time"), max_length=255)
    event_end = models.CharField(_("event end date and time"), max_length=255)
    venue = models.ForeignKey(
        DonationVenue,
        on_delete=models.CASCADE,
        verbose_name=_("donation venue"),
        related_name='donation_event')


class DonationInvite(models.Model):
    id = models.AutoField(primary_key=True)
    event = models.ForeignKey(
        DonationEvent,
        on_delete=models.CASCADE,
        verbose_name=_("donation event"),
        related_name='donation_invite')
    confirmed = models.BooleanField(
        _('invitation is confirmed'), default=False)
    user = models.ForeignKey(
        User,
        on_delete=models.DO_NOTHING,
        verbose_name=_("user"),
        related_name='user_invites',
        null=True)


class ConfirmedDonation(models.Model):
    id = models.AutoField(primary_key=True)
    event = models.ForeignKey(
        DonationEvent,
        on_delete=models.CASCADE,
        verbose_name=_("donation event"),
        related_name='cd_event')
    user = models.ForeignKey(
        User,
        on_delete=models.DO_NOTHING,
        verbose_name=_("user"),
        related_name='user_donations',
        null=True)

krvjezivot/common/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from krvjezivot.users.models import User


class Notification(models.Model):
    id = models.AutoField(primary_key=True)
    assigned_to = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name=_("the user notification is assigned to"))
    text = models.CharField(_("text"), max_length=100)
    timestamp = models.DateTimeField(auto_now_add=True)
    seen = models.BooleanField(_("is seen"), default=False)
    link = models.CharField(_("link"), max_length=100, default='dashboard')
    faicon = models.CharField(_('fa icon'), max_length=20, default='warning')
    color = models.CharField(_('color'), max_length=20, default='yellow')

    class Meta:
        ordering = ['timestamp']


class AppAttribute(models.Model):
    id = models.AutoField(primary_key=True)
    key = models.CharField(_("attribute key"), max_length=255)
    py_type = models.CharField(_("python type"), max_length=255)
    value = models.CharField(_("value as string"), max_length=255)

krvjezivot/donations/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

# from enumfields import EnumField

# Create your models here.

krvjezivot/administration/forms.py
from django import forms

from .models import DonationEvent, DonationVenue


class DonationVenueForm(forms.ModelForm):
    class Meta:
        model = DonationVenue
        fields = ['name', 'address']


class DonationEventForm(forms.ModelForm):
    class Meta:
        model = DonationEvent
        fields = ['name', 'event_start', 'event_end', 'venue']

    def __init__(self, *args, **kwargs):
        super(DonationEventForm, self).__init__(*args, **kwargs)
        self.fields['venue'].choices = [
            (v.pk, v.name) for v in DonationVenue.objects.all()
        ]

        self.fields['event_start'].widget.attrs['class'] = 'im-datetime'
        self.fields['event_end'].widget.attrs['class'] = 'im-datetime'
        self.fields['venue'].widget.attrs['class'] = 'select2'

krvjezivot/administration/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views import View
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.decorators.http import require_POST, require_GET
from django.views.decorators.csrf import csrf_exempt

from krvjezivot.users.models import User
from krvjezivot.users.enums import Sex

from .forms import DonationEventForm, DonationVenueForm
from .models import DonationEvent, DonationVenue, DonationInvite, ConfirmedDonation

# Create your views here.


@require_GET
@login_required
def get_donation_venues_list(request):
    donation_venues_list = DonationVenue.objects.all()
    return render(request, 'administration/donation-venues-list.html',
                  {'donation_venues_list': donation_venues_list})


class DonationVenueFormView(LoginRequiredMixin, View):
    form_class = DonationVenueForm
    instance = DonationVenue()
    template_name = 'administration/donation_venue_add_update_partial.html'

    def get(self, request, venue_id=None, *args, **kwargs):
        if venue_id is not None:
            dv = get_object_or_404(DonationVenue, pk=venue_id)
            self.instance = dv
        form = self.form_class(instance=self.instance)
        return render(request, self.template_name, {
            'form': form,
            'venue_id': venue_id
        })

    def post(self, request, venue_id=None, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            if venue_id is not None:
                self.instance = get_object_or_404(DonationVenue, pk=venue_id)
                form = self.form_class(request.POST, instance=self.instance)
            form.save()
            return HttpResponseRedirect(
                reverse('administration:donation_venues_list'))
        return render(request, self.template_name, {
            'form': form,
            'venue_id': venue_id
        })


@require_POST
@login_required
def donation_venue_delete(request, venue_id=None, *args, **kwargs):
    if venue_id is not None:
        instance = get_object_or_404(DonationVenue, pk=venue_id)
        instance.delete()
    return HttpResponseRedirect(reverse('administration:donation_venues_list'))


@require_GET
@login_required
def get_donation_events_list(request):
    donation_events_list = DonationEvent.objects.all()
    return render(request, 'administration/donation_events_list.html',
                  {'donation_events_list': donation_events_list})


class DonationEventFormView(LoginRequiredMixin, View):
    form_class = DonationEventForm
    instance = DonationEvent()
    template_name = 'administration/donation_event_add_update_partial.html'

    def get(self, request, event_id=None, *args, **kwargs):
        if event_id is not None:
            de = get_object_or_404(DonationEvent, pk=event_id)
            self.instance = de
        form = self.form_class(instance=self.instance)
        return render(request, self.template_name, {
            'form': form,
            'event_id': event_id
        })

    def post(self, request, event_id=None, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            if event_id is not None:
                self.instance = get_object_or_404(DonationEvent, pk=event_id)
                form = self.form_class(request.POST, instance=self.instance)
            evnt = form.save()
            self.send_invitations(request, evnt)
            return HttpResponseRedirect(
                reverse('administration:donation_events_list'))
        return render(request, self.template_name, {
            'form': form,
            'event_id': event_id
        })

    def send_invitations(self, request, evnt):
        users = [
            usr for usr in User.objects.all()
            if usr.get_days_since_last_donation > 90 and usr.sex == Sex.MALE
            or usr.get_days_since_last_donation > 90 and usr.sex == Sex.FEMALE
        ]
        for user in users:
            DonationInvite.objects.create(event=evnt, user=request.user)


@require_POST
@login_required
def donation_event_delete(request, event_id=None, *args, **kwargs):
    if event_id is not None:
        instance = get_object_or_404(DonationEvent, pk=event_id)
        instance.delete()
    return HttpResponseRedirect(reverse('administration:donation_events_list'))


@require_GET
@login_required
def get_donation_qr_confirm(request, event_id=None, *args, **kwargs):
    if event_id is not None:
        instance = get_object_or_404(DonationEvent, pk=event_id)
    return render(request, 'administration/qrcode_confirm.html',
                  {'event': instance})


@csrf_exempt
@login_required
def user_donation_qr_confirm(request, event_id=None, *args, **kwargs):
    uname = request.POST.get("username", "")

    user_for_confirm = get_object_or_404(User, username=uname)
    evnt_for_confirm = get_object_or_404(DonationEvent, id=event_id)
    invitation = get_object_or_404(
        DonationInvite, event_id=event_id, user=user_for_confirm)

    if invitation.confirmed is True:
        ConfirmedDonation.objects.create(
            user=user_for_confirm, event=evnt_for_confirm)

    return HttpResponseRedirect(
        reverse('administration:get_donation_qr_confirm'),
        {'event': evnt_for_confirm})

krvjezivot/donations/views.py
from django.shortcuts import render
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views import View
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.decorators.http import require_POST, require_GET

from krvjezivot.users.models import User
from krvjezivot.users.enums import Sex

from krvjezivot.administration.forms import DonationEventForm, DonationVenueForm
from krvjezivot.administration.models import DonationEvent, DonationVenue, DonationInvite, ConfirmedDonation

# Create your views here.


@require_GET
@login_required
def get_donation_invites_list(request):
    donation_invites_pending = DonationInvite.objects.filter(
        user=request.user, confirmed=False)
    donation_invites_confirmed = DonationInvite.objects.filter(
        user=request.user, confirmed=True)

    return render(
        request, 'donations/invites_list.html', {
            'donation_invites_pending': donation_invites_pending,
            'donation_invites_confirmed': donation_invites_confirmed
        })


@require_POST
@login_required
def donation_invite_confirm(request, invite_id=None, *args, **kwargs):
    inv = get_object_or_404(DonationInvite, id=invite_id)
    inv.confirmed = True
    inv.save()
    return HttpResponseRedirect(reverse('donations:donation_invites_list'))


@require_POST
@login_required
def donation_invite_delete(request, invite_id=None, *args, **kwargs):
    if invite_id is not None:
        inv = get_object_or_404(DonationInvite, id=invite_id)
        inv.delete()
    return HttpResponseRedirect(reverse('donations:donation_invites_list'))


@require_GET
@login_required
def get_qrcode(request):
    return render(request, 'donations/qrcode.html')


@require_GET
@login_required
def get_donation_history(request, *args, **kwargs):
    donations = ConfirmedDonation.objects.filter(user=request.user)
    return render(request, 'donations/donations_history.html',
                  {'donations': donations})

krvjezivot/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, RedirectView, UpdateView

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):
    fields = ["full_name", ]
    model = User

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)

krvjezivot/templates/partials/appname.html
<b>K</b>rv <b>J</b>e <b>Ž</b>ivot

krvjezivot/templates/partials/appname_mini.html
<b>kjž</b>

krvjezivot/templates/partials/control_sidebar.html
<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
  <!-- Create the tabs -->
  <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
    <li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
    <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
  </ul>
  <!-- Tab panes -->
  <div class="tab-content">
    <!-- Home tab content -->
    <div class="tab-pane active" id="control-sidebar-home-tab">
      <h3 class="control-sidebar-heading">Recent Activity</h3>
      <ul class="control-sidebar-menu">
        <li>
          <a href="javascript:;">
            <i class="menu-icon fa fa-birthday-cake bg-red"></i>
            <div class="menu-info">
              <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>
              <p>Will be 23 on April 24th</p>
            </div>
          </a>
        </li>
      </ul>
      <!-- /.control-sidebar-menu -->

      <h3 class="control-sidebar-heading">Tasks Progress</h3>
      <ul class="control-sidebar-menu">
        <li>
          <a href="javascript:;">
            <h4 class="control-sidebar-subheading">
              Custom Template Design
              <span class="pull-right-container">
                  <span class="label label-danger pull-right">70%</span>
                </span>
            </h4>
            <div class="progress progress-xxs">
              <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
            </div>
          </a>
        </li>
      </ul>
      <!-- /.control-sidebar-menu -->

    </div>
    <!-- /.tab-pane -->
    <!-- Stats tab content -->
    <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
    <!-- /.tab-pane -->
    <!-- Settings tab content -->
    <div class="tab-pane" id="control-sidebar-settings-tab">
      <form method="post">
        <h3 class="control-sidebar-heading">General Settings</h3>
        <div class="form-group">
          <label class="control-sidebar-subheading">
            Report panel usage
            <input type="checkbox" class="pull-right" checked>
          </label>
          <p>
            Some information about this general settings option
          </p>
        </div>
        <!-- /.form-group -->
      </form>
    </div>
    <!-- /.tab-pane -->
  </div>
</aside>
<!-- /.control-sidebar -->

<!-- Add the sidebar's background. This div must be placed immediately after the control sidebar -->
<div class="control-sidebar-bg"></div>

krvjezivot/templates/partials/footer.html
<!-- Main Footer -->
<footer class="main-footer">
  <!-- To the right -->
  <div class="pull-right hidden-xs">
    <!-- Anything you want -->
    <a href="{% url 'contact' %}">Contact</a> -
    <a href="{% url 'terms' %}">Terms</a> -
    <a href="{% url 'privacy' %}">Privacy</a>
  </div>
  <!-- Default to the left -->
  <strong>Copyright &copy; 2018 <a href="{% url 'home' %}">{% include 'partials/appname.html' %}</a>.</strong> All rights reserved.
</footer>

krvjezivot/templates/partials/notifications_menu.html
<!-- Notifications Menu -->
<li class="dropdown notifications-menu">
  <!-- Menu toggle button -->
  <a class="dropdown-toggle" data-toggle="dropdown">
    <i class="fa fa-bell-o"></i>
    {% if notifications_new_cnt > 0 %}
      <span class="label label-warning">{{ notifications_new_cnt }}</span>
    {% endif %}
  </a>
  <ul class="dropdown-menu">
    <li class="header">You have {{ notifications_new_cnt }} new notifications</li>
    <li>
      <!-- Inner Menu: contains the notifications -->
      <ul class="menu">
        {% for notif in notifications_list|slice:"0:5" %}
          <li class="{% if not notif.seen %}notification-new{% endif %}">
            <!-- start notification -->
            <a href="{{ notif.link }}">
              <i class="fa fa-{{ notif.faicon }} text-{{ notif.color }}"></i> {{ notif.text }}
            </a>
          </li>
        {% endfor %}
        <!-- end notification -->
      </ul>
    </li>
    {% if notifications_new_cnt > 5 %}
      <li class="footer"><a href="#">View all</a></li>
    {% endif %}
  </ul>
</li>

krvjezivot/templates/partials/sidebar_menu.html
{% load i18n %}
{% load static %}

<!-- Sidebar user panel (optional) -->
<div class="user-panel">
  <div class="pull-left image">
    <img src="{% static 'images/user.svg' %}" class="img-circle" alt="User Image">
  </div>
  <div class="pull-left info">
    <p>{{ user.username }}</p>
    <!-- Status -->
    <a><i class="fa fa-circle text-success"></i> {% trans "Online" %}</a>
  </div>
</div>

<!-- search form (Optional) -->
<form action="#" method="get" class="sidebar-form">
  <div class="input-group">
    <input type="text" name="q" class="form-control" placeholder="Search...">
    <span class="input-group-btn">
        <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
        </button>
      </span>
  </div>
</form>
<!-- /.search form -->

<!-- Sidebar Menu -->
<ul class="sidebar-menu" data-widget="tree" data-accordion="false">
  <li class="header">GENERAL</li>
  <li>
    <a href="{% url 'dashboard' %}"><i class="fa fa-dashboard"></i> <span>Dashboard</span></a>
  </li>
  {% if request.user.is_superuser %}
    <li class="header">VENUES</li>
    <li>
      <a href="{% url 'administration:donation_venues_list' %}"><i class="fa fa-hospital-o"></i> <span>Donation Venues</span></a>
    </li>
    <li>
      <a id="donation-venue-add-button"><i class="fa fa-plus"></i> <span>Create Donation Venue</span></a>
    </li>
    <li class="header">EVENTS</li>
    <li>
      <a href="{% url 'administration:donation_events_list' %}"><i class="fa fa-calendar-o"></i> <span>Donation Events</span></a>
    </li>
    <li>
      <a id="donation-event-add-button"><i class="fa fa-plus"></i> <span>Create Donation Event</span></a>
    </li>
  {% else %}
    <li class="header">INVITATIONS</li>
    <li>
      <a href="{% url 'donations:donation_invites_list' %}"><i class="fa fa-envelope-o"></i> <span>Donation Invites</span></a>
    </li>
    <li>
      <a href="{% url 'donations:user_qrcode' %}"><i class="fa fa-qrcode"></i> <span>QR Code</span></a>
    </li>
    <li class="header">HISTORY</li>
    <li>
      <a href="{% url 'donations:donation_history' %}"><i class="fa fa-tint"></i> <span>Donations</span></a>
    </li>
  {% endif %}
</ul>
<!-- /.sidebar-menu -->

krvjezivot/templates/partials/user_account_menu.html
{% load i18n %}
{% load static %}

<!-- User Account Menu -->
<li class="dropdown user user-menu">
  <!-- Menu Toggle Button -->
  <a class="dropdown-toggle" data-toggle="dropdown">
    <!-- The user image in the navbar-->
    <img src="{% static 'images/user.svg' %}" class="user-image" alt="User Image">
    <!-- hidden-xs hides the username on small devices so only the image appears. -->
    <span class="hidden-xs">{{ user.username }}</span>
  </a>
  <ul class="dropdown-menu">
    <!-- Menu Footer-->
    <li class="user-footer">
      <div class="pull-left">
        <a href="{% url 'users:detail' request.user.username  %}" class="btn btn-primary btn-flat">{% trans "Profile" %}</a>
      </div>
      <div class="pull-right">
        <a href="{% url 'account_logout' %}" class="btn btn-danger btn-flat">{% trans "Sign Out" %}</a>
      </div>
    </li>
  </ul>
</li>